name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest
          pip install pytest-cov
          pip install pytest-cases
      - name: Run tests with pytest
        run: |
          python -m pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=equity_risk_model --cov-report=xml --cov-report=html
          coverage report -m
      - name: Run coverage
        run: |
          coverage report -m
